[pytest]
log_cli= true
log_level = INFO
log_cli_level = INFO
addopts= --strict-markers --tb=short
markers= login: Login test cases
    home: Home page test cases
    order: Specify execution order
    cameras_list_display: Valid cameras table
    single_view: Single view page test